import { calculateZodiacScores } from '../src/utils/zodiacScoring';

describe('calculateZodiacScores', () => {
  const eligiblePokemon = {
    rat: ['pikachu'],
    ox: ['tauros'],
    tiger: ['zangoose'],
    rabbit: ['buneary'],
    dragon: ['magikarp'],
    snake: ['seviper'],
    horse: ['ponyta', 'horsea', 'blitzle'],
    goat: ['mareep'],
    monkey: ['mankey'],
    rooster: ['pidgey'],
    dog: ['growlithe'],
    pig: ['spoink'],
  };

  const teamDefinitions = [
    { key: 'alpha', name: 'Alpha Team' },
    { key: 'beta', name: 'Beta Team' },
  ];

  const teamMembers = {
    alpha: ['Ash', 'Misty'],
    beta: ['Brock'],
  };

  it('awards unique evolution bonuses and applies duplicate penalties across a team', () => {
    const scoring = calculateZodiacScores({
      eligiblePokemon,
      teamDefinitions,
      teamMembers,
      shinies: [
        {
          id: '1',
          pokemonName: 'seviper',
          name: 'Seviper',
          trainerName: 'Ash',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-20',
          createdAt: '2026-03-20T01:00:00.000Z',
          points: 10,
        },
        {
          id: '2',
          pokemonName: 'seviper',
          name: 'Seviper',
          trainerName: 'Misty',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-21',
          createdAt: '2026-03-21T01:00:00.000Z',
          points: 10,
        },
      ],
    });

    expect(scoring.teams['Alpha Team'].catchPoints).toBe(11);
    expect(scoring.teams['Alpha Team'].uniqueSpeciesBonus).toBe(3);
    expect(scoring.teams['Alpha Team'].bonusPoints).toBe(3);
    expect(scoring.teams['Alpha Team'].score).toBe(14);
    expect(scoring.teams['Alpha Team'].trainerPoints).toEqual({
      Ash: 10,
      Misty: 1,
    });
  });

  it('awards horse and full zodiac bonuses only to the first eligible team', () => {
    const scoring = calculateZodiacScores({
      eligiblePokemon,
      teamDefinitions,
      teamMembers,
      shinies: [
        {
          id: '1',
          pokemonName: 'ponyta',
          name: 'Ponyta',
          trainerName: 'Ash',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-20',
          createdAt: '2026-03-20T01:00:00.000Z',
          points: 6,
        },
        {
          id: '2',
          pokemonName: 'horsea',
          name: 'Horsea',
          trainerName: 'Ash',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-20',
          createdAt: '2026-03-20T02:00:00.000Z',
          points: 6,
        },
        {
          id: '3',
          pokemonName: 'blitzle',
          name: 'Blitzle',
          trainerName: 'Ash',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-20',
          createdAt: '2026-03-20T03:00:00.000Z',
          points: 6,
        },
        {
          id: '4',
          pokemonName: 'pikachu',
          name: 'Pikachu',
          trainerName: 'Ash',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-20',
          createdAt: '2026-03-20T04:00:00.000Z',
          points: 10,
        },
        {
          id: '5',
          pokemonName: 'tauros',
          name: 'Tauros',
          trainerName: 'Ash',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-20',
          createdAt: '2026-03-20T05:00:00.000Z',
          points: 10,
        },
        {
          id: '6',
          pokemonName: 'zangoose',
          name: 'Zangoose',
          trainerName: 'Ash',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-20',
          createdAt: '2026-03-20T06:00:00.000Z',
          points: 10,
        },
        {
          id: '7',
          pokemonName: 'buneary',
          name: 'Buneary',
          trainerName: 'Ash',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-20',
          createdAt: '2026-03-20T07:00:00.000Z',
          points: 10,
        },
        {
          id: '8',
          pokemonName: 'magikarp',
          name: 'Magikarp',
          trainerName: 'Ash',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-20',
          createdAt: '2026-03-20T08:00:00.000Z',
          points: 10,
        },
        {
          id: '9',
          pokemonName: 'seviper',
          name: 'Seviper',
          trainerName: 'Ash',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-20',
          createdAt: '2026-03-20T09:00:00.000Z',
          points: 10,
        },
        {
          id: '10',
          pokemonName: 'mareep',
          name: 'Mareep',
          trainerName: 'Ash',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-20',
          createdAt: '2026-03-20T10:00:00.000Z',
          points: 10,
        },
        {
          id: '11',
          pokemonName: 'mankey',
          name: 'Mankey',
          trainerName: 'Ash',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-20',
          createdAt: '2026-03-20T11:00:00.000Z',
          points: 10,
        },
        {
          id: '12',
          pokemonName: 'pidgey',
          name: 'Pidgey',
          trainerName: 'Ash',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-20',
          createdAt: '2026-03-20T12:00:00.000Z',
          points: 10,
        },
        {
          id: '13',
          pokemonName: 'growlithe',
          name: 'Growlithe',
          trainerName: 'Ash',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-20',
          createdAt: '2026-03-20T13:00:00.000Z',
          points: 10,
        },
        {
          id: '14',
          pokemonName: 'spoink',
          name: 'Spoink',
          trainerName: 'Ash',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-20',
          createdAt: '2026-03-20T14:00:00.000Z',
          points: 10,
        },
        {
          id: '15',
          pokemonName: 'ponyta',
          name: 'Ponyta',
          trainerName: 'Brock',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-21',
          createdAt: '2026-03-21T01:00:00.000Z',
          points: 6,
        },
        {
          id: '16',
          pokemonName: 'horsea',
          name: 'Horsea',
          trainerName: 'Brock',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-21',
          createdAt: '2026-03-21T02:00:00.000Z',
          points: 6,
        },
        {
          id: '17',
          pokemonName: 'blitzle',
          name: 'Blitzle',
          trainerName: 'Brock',
          imageUrl: '',
          isFailed: false,
          isSecret: false,
          isAlpha: false,
          encounterType: 'single',
          totalEncounters: null,
          catchDate: '2026-03-21',
          createdAt: '2026-03-21T03:00:00.000Z',
          points: 6,
        },
      ],
    });

    expect(scoring.teams['Alpha Team'].horseZodiacBonus).toBe(6);
    expect(scoring.teams['Alpha Team'].fullZodiacBonus).toBe(12);
    expect(scoring.teams['Alpha Team'].claimedBonuses).toEqual([
      'Horse Zodiacs +6',
      '12 Zodiacs +12',
    ]);
    expect(scoring.teams['Beta Team'].horseZodiacBonus).toBe(0);
    expect(scoring.teams['Beta Team'].fullZodiacBonus).toBe(0);
  });
});
